### PR TITLE
Fixed history visibility

### PR DESCRIPTION
**Pull request by sf-pixel**
Fixed PR. Change link color to white, fix weird spacing in the history tab.

### CODE REVIEW

**Comment by kylegrover** [comment]
@Pixel10312 could you fix that conflict and/or post a screenshot of the changes?

**Comment by sf-pixel** [comment]
@kylegrover here it is.
image
image

**Comment by CSEEEE** [comment]
The history is not appearing for my nft. OBJKT#301426 

Additionally the NFT is for sale on OBJKT, but states it is not for sale on HEN. 

Thank you!

**Comment by sf-pixel** [comment]
Branch closed due to new development with post-hicathon WG UI-UX

**Pull request closed without merging**
