### PR TITLE
Change default storage to prevent backtracks

### PR DESCRIPTION
**Pull request by sf-pixel**
Default storage was not set within the v2 swaps function, adding ```{ storageLimit: 209 }``` to the ```.send()``` function sets the default storage to 209 (the most storage that has been used with swaps AFAIK) instead of the default.

### CODE REVIEW

**Comment by BitPsycho** [comment]
The storage fee field should just be editable imo.  Before I always had put it to 400 as below that I still occasionaly had backtracking issues.

**Comment by sf-pixel** [comment]
> The storage fee field should just be editable imo.  Before I always had put it to 400 as below that I still occasionaly had backtracking issues.

It is editable, this just prevents the default from being _below_ 209

**Comment by skenaja** [comment]
I don't think that Temple allows editable storage (yet?) on batch tx (a v2 swap is an [update_operator + swap tx](https://better-call.dev/mainnet/opg/opTWqA9bW1TsfmuVdK6tsRXqUHXFrkNpHVvsTPXJN9HpDJKeuqV/contents))

**Comment by sf-pixel** [comment]
> I don't think that Temple allows editable storage (yet?) on batch tx (a v2 swap is an [update_operator + swap tx](https://better-call.dev/mainnet/opg/opTWqA9bW1TsfmuVdK6tsRXqUHXFrkNpHVvsTPXJN9HpDJKeuqV/contents))

ah, wasn't aware that temple didn't allow that, I mainly use Kukai so that's why... that said, since storage is only consumed on an as-needed basis, how much higher should I increase the storageLimit to ensure most if not all swaps go thru? I honestly don't know since I do swaps thru a script with 1000 as my limit.

**Comment by crzypatchwork** [comment]
I've tried a similar solution but I was not able to see it picking up in the raw transaction. A similar solution was presented by nft biker also which was recently uploaded.

**Comment by BitPsycho** [comment]
> I don't think that Temple allows editable storage (yet?) on batch tx (a v2 swap is an [update_operator + swap tx](https://better-call.dev/mainnet/opg/opTWqA9bW1TsfmuVdK6tsRXqUHXFrkNpHVvsTPXJN9HpDJKeuqV/contents))

Ah wasn't aware of that .. if that is the case then they should just default to a high number no ?  If I understood this whole storage fee then only what is really used is payed for anyways ?  ( On a side note - anyone have a good link that describes the storage feel concept on the Tezos blockchain and how it relates to gas fees ? )

**Comment by BitPsycho** [comment]
> > I don't think that Temple allows editable storage (yet?) on batch tx (a v2 swap is an [update_operator + swap tx](https://better-call.dev/mainnet/opg/opTWqA9bW1TsfmuVdK6tsRXqUHXFrkNpHVvsTPXJN9HpDJKeuqV/contents))
> 
> ah, wasn't aware that temple didn't allow that, I mainly use Kukai so that's why... that said, since storage is only consumed on an as-needed basis, how much higher should I increase the storageLimit to ensure most if not all swaps go thru? I honestly don't know since I do swaps thru a script with 1000 as my limit.

Yeah been using 350 before v2 and that always worked fine.

**Comment by sf-pixel** [comment]
PR is closed thanks to a solution from @nftbiker.

**Pull request closed without merging**
