### PR TITLE
Decoded SUBJKTS in the URL

### PR DESCRIPTION
**Pull request by sf-pixel**
Spaces, special characters and any otherwise broken profile links are now decoded before sending SUBJKT query. Decided to do the PR against the main as I've added less than 20 characters.

### CODE REVIEW

**Comment by kylegrover** [comment]
Can you give an example of a broken subjkt that this fixes so I can test it? Also it seems to break if you feed it an invalid subjkt, might need some error handling.

image

**Comment by sf-pixel** [comment]
> Can you give an example of a broken subjkt that this fixes so I can test it? Also it seems to break if you feed it an invalid subjkt, might need some error handling.
> 
> image
> 

Didn't see that coming, will for sure be adding validation into it, wasn't completely sure on broken accounts that are still broken (since a lot of people changed their subjkts to omit spaces recently) but query 30 or so subjkts on hicdex and you'll have one with spaces in between (currently displayed as: name%20ending) where the subjkt is properly encoded but never decoded.

**Comment by kylegrover** [comment]
`/Yuvraj Imaginaria` is an example I found, seems to work! I think if you get the error handling fixed this should be merged.

**Comment by sf-pixel** [comment]
@kylegrover invalid SUBJKTs now redirect to the feed.

**Pull request merged**
