### PR TITLE
Directly link to users' collection via `/tz/:id/:collection`

### PR DESCRIPTION
**Pull request by skenaja**
* Allow users to link directly to their collection with `/tz/:id/collection`
* Tabs onClick sets appropriate uri
* Default path is creations.

Implements https://github.com/hicetnunc2000/hicetnunc/issues/427

### CODE REVIEW

**Comment by skenaja** [comment]
Ad4vYR9LKI

**Review by andrevenancio — APPROVED** [review]
Looks good.

**Comment by andrevenancio** [comment]
@crzypatchwork what do u think?

**Comment by hetnxyz** [comment]
Hi amazing team! Do you know when this one is scheduled to be released by any chance?
Many thanks!

**Comment by andrevenancio** [comment]
I've merged this, but it doesn't seem to work @skenaja !

**Pull request merged**
