### PR TITLE
Add a gallery for the Cronopios, a group of H=N early adopters

### PR DESCRIPTION
**Pull request by jackrusher**
As discussed last night and today on Twitter. :)

### CODE REVIEW

**Comment by andrevenancio** [comment]
can you link to those discussions?

**Comment by jackrusher** [comment]
@andrevenancio Sure! 😊 Lionel Radisson (@MAKIO135) [proposed](https://twitter.com/MAKIO135/status/1387505068472217600) the idea. The official HEN account [told us what to do](https://twitter.com/hicetnunc2000/status/1387505763875270657). The conversation went on for at least a million replies, but @crzypatchwork chimed in approvingly several times.

**Comment by MAKIO135** [comment]
https://twitter.com/MAKIO135/status/1387510893383192580 :)

**Comment by jackrusher** [comment]
Thanks, @andrevenancio :)

**Comment by schwittlick** [comment]
I am just noticing this is real. Thank you @jackrusher for handling things!

**Comment by MAKIO135** [comment]
💯💯💯

**Comment by andrevenancio** [comment]
I've approved after checking in with Rafael, as I though new galleries would have to be coming through smart contracts. How does one join the weirdos? is the weirdos a list of artists that @jackrusher defined in his tweet? or are they artists that joined before a certain OBJKT number? I'm confused 😸

**Comment by jackrusher** [comment]
@andrevenancio It's all an accident starting from a reply I made to a "which artists should I check out" tweet. I'd like to use it to experiment with community curation, the terms of which I'll propose the current group members once it's online. :)

**Comment by fraguada** [comment]
With all due respect to the artists (who I all admire) I can't see the justification for this gallery. The list of artists are not _only_ the first artists as there are other artists that started on the platform before many of the artists listed here. It is also not a very diverse list of artists, being made up of mostly white males. I propose to revert this PR until a more reasoned and available approach to adding galleries is conceived.

NOTE: the list of artists I am referring to was posted in discord: https://discord.com/channels/759930487946215444/836582504835186749/839566072314069042

cc @violetforest @andrevenancio @crzypatchwork

**Comment by andrevenancio** [comment]
Okay... I should had replied yesterday before this heated up but work commitments didn't allow for much time, so apologies for the late reply.

A few notes on how the galleries are currently implemented and why they're not ready to scale for everyone interested in creating their own.

But first a bit of context why the galleries were created in the first place: 

The FEN organisers (Joanie and Juliette) were contacting Artists and Collectors in an effort to bring more people to Tezos and Clean NFT. We sympatished quite a lot with the cause and decided to try to accomodate their effort to bring new artists to a more clean blockchain. Artists like Memo Akten, Golan, Patricio Gonzalez Vivo, Zach Lieberman, amongst many others. 

This did two things:

1. Brought more awareness to hicetnunc which benefits the whole community.

2. We could test if galleries/lists were something the community would want. And it seems like they (we) do.

Now, in order to accomodate the launch date for The FEN we decided to make the galleries static, while we work on a more long term solution using smart contracts.

As we finished developing for the galleries, I thought it was only fair to include the other 2 events that (up until then) have also happen on the platform. Pupila Dilatada, and Objkt4Objkt.

Several people online asked me how to publish a gallery, and I've replied - we're working on a way for anyone to be able to do it, and it will be available soon.

There's a lot of parallel features that need to happen in order for it to be ready and though it seems like the galleries are ready, they're not and that's simply because they weren't build to scale and having hundreds of objkts simply overwhelms the API. 

Here's why:

For each OBJKT in the gallery there are 2 API requests. So if your gallery has 30 OBJKT we're doing 60 API requests per user!

This is very different from the type of API response we currently have on the feed/tags where with a single API request we return 30 OBJKT.

Why? Well there's currently no way of grouping OBJKTs together.

There has been an effort for the last couple of weeks of building a database. Though initially it was done to bring tags, search and speed up the website experience. Building a database will allow us to introduce many new features including grouping objkt together.

But there's still work to be done and I'm not able to share a timeline to when its going to be available because it requires multiple people working on it across several different continents and timezones. So its hard to coordinate.

Now, going back to your concerns, part of my responsibilities is to review PR's and I can't be aware of all conversation that happen across the platform, it seems like there was a conversation that happen (mentioned above) that approved this feature, and hence I merged it. Now, the fact that is merged doesn't mean its published in production. And if you notice the source code there's a few other galleries that are on the source code but aren't published. So I do sympathise with your concerns @fraguada and others, and we are not trying to gate keep anyone from having a gallery, but there are currently technical reasons (which I mention above) which make it impossible to allow people to create galleries right now via static json files because they're not optimised. We're working very hard to make them available asap and appreciate your patience. 

Hope it helps clarify things a bit.

**Pull request merged**
