### PR TITLE
META - New feed, cache, curate, speeeeeeed

### PR DESCRIPTION
**Pull request by veqtor**
To go with:
https://github.com/hicetnunc2000/hicetnunc-api/pull/22

### CODE REVIEW

**Comment by veqtor** [comment]
WIP, going to add recommended curate amt

**Comment by veqtor** [comment]
This PR now covers lots of changes that just makes everything a lot better when we release the new API version 1.2.2

**Comment by veqtor** [comment]
New API deployed so ready to merge finally, but I want you guys to test it first:
@andrevenancio 
@crzypatchwork 
@pichiste

**Comment by andrevenancio** [comment]
conflicts can you fix it and I can merge this? the api has been merged right?

**Pull request merged**
