### PR TITLE
Switching to Infura IPFS to fix video playback on HTML OBJKTs

### PR DESCRIPTION
**Pull request by pichiste**
It was reported (https://github.com/hicetnunc2000/hicetnunc/issues/351) that it's not possible to load video files in HTML OBJKTs due to the inability to stream video from Cloudflare IPFS. 

@veqtor suggested we switch to Infura IPFS and this works!

This PR switches the source for both HTML and Video OBJKTs to use Infura IPFS (the latter was using ipfs.io).

### CODE REVIEW

**Comment by veqtor** [comment]
NIIIICEEE

**Comment by pichiste** [comment]
Upon @veqtor's suggestion, this now uses Infura's [subdomains](https://blog.infura.io/ipfs-0-5-is-here-with-a-new-improved-gateway/) directly, meaning each HTML OBJKT can be accessed at it's own subdomain.

For example:
https://bafybeifhhn5x7wf67chzpj6rrkxukf43nckjx7pvnddkoajib52rhu5mai.ipfs.infura-ipfs.io/

Still to be determined if and how this affects permissions for things like camera, mic, etc in the future, when embedded on hicetnunc.

**Comment by andrevenancio** [comment]
You mention you have something written about what you can/can't do. Do you mind adding a .md file with what you have in the faq folder? Then @violetforest can double check if everything makes sense and we then have a place to point people to read about best practices on HTML NFT.

**Comment by andrevenancio** [comment]
Also this doesn't break the video component does it?

**Comment by pichiste** [comment]
No I've checked it

**Comment by pichiste** [comment]
Re: doc, let me get it more polished and i'll make a new PR for that, sound ok?

**Comment by andrevenancio** [comment]
Yeah sounds good! Will merge this now then

**Review by andrevenancio — APPROVED** [review]

**Comment by violetforest** [comment]
HTML NFT readme would would be amazing

**Pull request merged**
