### PR TITLE
PDF support

### LINKED ISSUE #207: PDF Media Support
There was some discussion with **_devetec_** on Discord about the integration of PDFs into the site. Is this a possibility?

### PR DESCRIPTION
**Pull request by clemsos**
fixes #207

- also replaces #241

### CODE REVIEW

**Comment by andrevenancio** [comment]
conflicts

**Comment by clemsos** [comment]
ok resolved for merge

**Comment by andrevenancio** [comment]
thanks!

**Comment by clemsos** [comment]
thank you !

**Pull request merged**
