### PR TITLE
Switching to HTML ZIP file support

### PR DESCRIPTION
**Pull request by pichiste**
Switching from supporting HTML files to ZIP archives containing an index.html file and all related files/assets. The purpose is to make it easier for users to easily pack up their web project directories, rather than enforcing a single HTML file with inline scripts and assets.

@andrevenancio  The [preview](https://github.com/pichiste/hicetnunc/blob/feature/html-ipfs/src/components/media-types/html/index.js) on the mint page is now blank for this media type, since it would take a bit more work to get this working locally from a zip file (though I do have a working version of it using a service worker).

Upon clicking the mint button, the zip file is [unpacked and sanitized](https://github.com/pichiste/hicetnunc/blob/feature/html-ipfs/src/utils/html.js#L19) (directories and dot files removed, paths are truncated to location of index.html file, etc).

The index.html file also gets the CSP meta tag injected as before, to prevent external sources. Seems like we need some messaging around this so users aren't confused as to why a js library hosted on a cdn isn't loading, for example.

@veqtor I haven't been able to get the IPFS uploads working, but [here](https://github.com/pichiste/hicetnunc/blob/feature/html-ipfs/src/data/ipfs.js#L38) is my attempt if you want to have a look. The main issues are:
- Getting 403 forbidden errors from all calls to infura api
- What path should the directory be written to on IPFS?
- Should the metafile point to the directory or the index.html file on IPFS?

Also FYI minting is temporarily [disabled](https://github.com/pichiste/hicetnunc/blob/feature/html-ipfs/src/pages/mint/index.js#L102) until the upload stuff works.

### CODE REVIEW

**Comment by mrdoob** [comment]
Just wanted to share that recently I switched to [fflate](https://github.com/101arrowz/fflate) for zip/unzip in three.js (editor, loaders, etc) and I've been pretty happy with it 👍

**Comment by pichiste** [comment]
> Just wanted to share that recently I switched to [fflate](https://github.com/101arrowz/fflate) for zip/unzip in three.js (editor, loaders, etc) and I've been pretty happy with it 👍

Nice, that looks cleaner than [zip.js](https://github.com/gildas-lormeau/zip.js) which is currently used. Will see about switching over when there's a sec. Thanks!

**Comment by andrevenancio** [comment]
I'm merging this to develop to test. If its all good we can merge it. Any changes you need to do, please raise another PR

**Comment by gildas-lormeau** [comment]
> Nice, that looks cleaner than [zip.js](https://github.com/gildas-lormeau/zip.js) which is currently used. Will see about switching over when there's a sec. Thanks!

Hi, I'm the author of zip.js. I'm still trying to improve it. Out of curiosity, what did you find cleaner in fflate?

**Comment by pichiste** [comment]
> > Nice, that looks cleaner than [zip.js](https://github.com/gildas-lormeau/zip.js) which is currently used. Will see about switching over when there's a sec. Thanks!
> 
> Hi, I'm the author of zip.js. I'm still trying to improve it. Out of curiosity, what did you find cleaner in fflate?

Hi there, first of all thanks for the very useful library! We made the switch simply for the sake of keeping the code as minimal as possible, and fflate offers a simple `decompressSync` that doesn't require taking readers/writers/getData into account. You simply give it an input buffer, and get back the file buffers. Not really sure that zip.js needs something like that, but it would be handy!

**Comment by gildas-lormeau** [comment]
Thank you for the feedback. The main purposes of zip.js are to handle large files and to provide an API to easily handle custom source/destination of data (e.g. a connector to Google Drive or the proprietary FileSystem API in Chrome). That's why it does not provide methods to process data synchronously. By default, it processes data per block of 512KB. It's also written to be as readable and maintainable as possible. This can be useful for people who would like to fork it. The consequence is that it is larger than a library like fflate.

**Pull request merged**
