### PR TITLE
Feature - Add Tezos Profiles Verifications for Creators

### PR DESCRIPTION
**Pull request by obstropolos**
#### Description 

This change adds a badge to a creator's page if they have an existing Tezos Profile created using [the Tezos Profiles service](https://tzprofiles.com/). Additionally, it adds an alias and Twitter badge from a user's Tezos Profile if the user does not already have one from the existing [TzKT authentication service](https://baking-bad.org/blog/2021/05/01/f-a-q-hic-et-nunc/). The data is currently being pulled from the [Tezos Profiles API](https://github.com/spruceid/tzprofiles/tree/main/api/service).

[Tezos Profiles](https://github.com/spruceid/tzprofiles) and all of its components are completely open-source (including the indexer and API) and can easily be rehomed to any other server. Users choose what URLs are resolved to fetch and check their verifications and they can update their own smart contracts to new URLs at any time. This uses [TZIP-024](https://gitlab.com/tzip/tzip/-/blob/tzip-024/proposals/tzip-24/tzip-24.md) to ensure interoperability and protect user privacy. 

#### Progress 

- [x] Add the Tezos Profiles API
- [x] Add a badge for an existing Tezos Profile
- [x] Add a Twitter badge if no account is found using the TzKT service
- [x] Add an alias if none is found using the TzKT service  

A demo deployment of the service with the add-on can be found [here](https://a1b3165a.hicetnunc.pages.dev/).

The goal of this integration is to begin to add additional creator verifications to HEN profiles and help prevent copyminting.

#### Testing 
- [Example of an existing TzKT profile augmented with a Tezos Profile icon](https://a1b3165a.hicetnunc.pages.dev/tz/tz1P5Za1TUMsDejgzMM5iMNfHAxDUpPCHiwZ)
Screen Shot 2021-06-11 at 3 26 22 PM

- [Example of an existing Tezos Profile with no existing TzKT profile](https://a1b3165a.hicetnunc.pages.dev/tz/tz2Dvv6ib5wbtWkPghE2KdgHB9WXvoNxERQ8)
Screen Shot 2021-06-11 at 3 27 15 PM

#### Future Goals 

Eventually, we wish to augment the service with additional credentials for artists in order to better verify themselves. These credentials can include additional social profile verifications and even verifications from other blockchains. Additionally, we would like the HEN community to host their own API and indexer for Tezos Profiles, which only requires a modest server.

### CODE REVIEW

**Comment by crzypatchwork** [comment]
I would suggest to use alias in a different way to make profiles more accessible

for example: hicetnunc.xyz/crzypatchwork is way more accessible then hicetnunc.xyz/tz/tz1...

**Comment by veqtor** [comment]
> I would suggest to use alias in a different way to make profiles more accessible
> 
> for example: hicetnunc.xyz/crzypatchwork is way more accessible then hicetnunc.xyz/tz/tz1...

I would say yes, in the long run but this would need backend and more complex contract, also, is it really up to tzp to decide who gets which alias?

**Comment by crzypatchwork** [comment]
Screenshot from 2021-06-12 08-59-04

not sure if the tzprofile badge is working from the verification process I went through

https://tzkt.io/KT1SeUWpeioMYNaHZCwzUv5fKioLGd3y87Vw/operations/

**Comment by sbihel** [comment]
Looks like we have a bug on our side for accounts with many contracts, sorry about that.

**Comment by sbihel** [comment]
It has been fixed.

**Comment by obstropolos** [comment]
Hi @crzypatchwork, thanks for giving us the heads up. For accounts that had many contracts such as yours, the indexer was not behaving as expected. We have switched indexer endpoints and added pagination, which has addressed this.

https://github.com/spruceid/tzprofiles/pull/99

You should now be able to see the icon and other data here:
https://a1b3165a.hicetnunc.pages.dev/tz/tz1Y1j7FK1X9Rrv2VdPz5bXoU7SszF8W1RnK

**Pull request merged**
