### PR TITLE
fix small font issue

### PR DESCRIPTION
**Pull request by violetforest**

### CODE REVIEW

**Comment by crzypatchwork** [comment]
we are not going back to courier new I've misread the code change

**Comment by violetforest** [comment]
the new font is on the develop branch already, the font that was proposed by julio in the figma

people on twitter are complaining that this font change to monospace is too small and they cant read it. https://twitter.com/jamespowderly/status/1399795697617031169

**Comment by powderly** [comment]
The current font size is very small on the desktop in the profile Chrome Version 90.0.4430.212 (Official Build) (x86_64) on a Mac OS Catalina 10.15.7
Screen Shot 2021-06-01 at 1 33 50 PM
Screen Shot 2021-06-01 at 1 33 59 PM

**Comment by powderly** [comment]
// font-family: 'OCR A Std', monospace; // README: crzypatchwork, this font doesn't look great.
comment from the CSS LOL

**Pull request merged**
