### PR TITLE
Replaced LazyLoadImage with <img loading="lazy">

### PR DESCRIPTION
**Pull request by mrdoob**
May be too early for this though. Not yet supported in Safari:
https://caniuse.com/loading-lazy-attr

### CODE REVIEW

**Comment by mrdoob** [comment]
Did this land in the site? Or did it get reverted?

**Comment by mrdoob** [comment]
@andrevenancio Seem like this got lost in a refactor maybe? Should I do the PR again?

**Comment by andrevenancio** [comment]
We had to re-think it as we need to support safari and that wasn't working in safari. So now it's a mix of intersection observer and react lazy loader which comes with a polyfill. But as soon as safari supports this I'm happy to reduce the dependency stack.

**Comment by mrdoob** [comment]
How about this?

```js
export const ImageComponent = ({ src }) => {
  return (
    <div className={styles.container}>
      {/apple/i.test(navigator.vendor)
        ? <LazyLoadImage className={styles.image} src={src} alt="💥" />
        : <img className={styles.image} src={src} alt="💥" loading="lazy" />
      }
    </div>
  )
}
```

**Pull request merged**
