### PR TITLE
Fix for Safari/Firefox fullscreen on Desktop

### PR DESCRIPTION
**Pull request by pichiste**

### CODE REVIEW

**Comment by Pamicel** [comment]
Tested on safari 14.0 and FF 86.0 👍

my polite suggestion for a change is to use polyfills for `document.fullcreenElement` and `element.requestFullScreen`  at the top of `src/components/media-types/container.js` rather that polyfilling inside the code

**Review by Pamicel — APPROVED** [review]
Tested on safari 14.0 and FF 86.0 👍

**Comment by Pamicel** [comment]
Tested the updated code, still good

**Comment by andrevenancio** [comment]
minor conflict! don't know where that came from!

**Comment by pichiste** [comment]
@andrevenancio fixed!

**Review by andrevenancio — APPROVED** [review]

**Pull request merged**
