### PR TITLE
fixed about page spacing, added hicetnunc reddit.

### PR DESCRIPTION
**Pull request by Devetec**
fixed spacing, added hicetnunc reddit.

### CODE REVIEW

**Comment by Devetec** [comment]
And now, I cannot for the life of me figure out why package-lock.json shrunk by half.

**Comment by andrevenancio** [comment]
this page has been refactored. Can you make the buttons are showing where they should @Devetec ?

**Comment by Devetec** [comment]
Wait, they're not?

**Comment by Devetec** [comment]
> this page has been refactored. Can you make the buttons are showing where they should @Devetec ?

What do you mean?

**Review by andrevenancio — APPROVED** [review]

**Pull request merged**
