### PR TITLE
Interactive vector support

### PR DESCRIPTION
**Pull request by Devetec**
This should work, but my local development server isn't working? I can't view how the object page would look...

### CODE REVIEW

**Comment by andrevenancio** [comment]
Can you provide a link to an SVG?

**Comment by Devetec** [comment]
> Can you provide a link to an SVG?

https://rawgit.com/petercollingridge/code-for-blog/master/svg-interaction/interactive-map/colour_with_class.svg

A pretty simple interactive SVG!

**Comment by andrevenancio** [comment]
I mean a objkt to test this. Makio's link?

**Comment by MAKIO135** [comment]
https://www.hicetnunc.xyz/objkt/6124 :)

**Comment by andrevenancio** [comment]
this has been merged on [168](https://github.com/hicetnunc2000/hicetnunc/pull/168)

Thanks guys

**Pull request merged**
