### PR TITLE
Fix units of OBJKT's hdao balance and handle upstream API errors

### LINKED ISSUE #703: hDAO reclaim amount display issues
**Describe the bug**
2 small issues with the new claim_hDAO feature on OBJKT page for creators, raised via Discord
https://discord.com/channels/759930487946215444/837237944208326667/843508469080391691

1. If the API doesn't return a value, the UI shows `-1`:

image

2 - The UI shows the value in microtez, not tez

image

Expected behaviour:

1. make the button behave as if the objkt has 0 hdao (so default behaviour)
2. divide the amount by 1,000,000 (as per user profile page)

### PR DESCRIPTION
**Pull request by skenaja**
Fixes #703

### CODE REVIEW

**Comment by skenaja** [comment]
Resolved conflicts
Added tooltip display logic.

**Comment by violetforest** [comment]
@skenaja i think this needs null checks, its currently breaking when I pull the latest develop, probably because i"m not synced

Screen Shot 2021-05-20 at 2 15 57 PM

Screen Shot 2021-05-20 at 2 13 52 PM

Screen Shot 2021-05-20 at 2 14 05 PM

**Comment by violetforest** [comment]
I just uncommented  ```{renderHDAObutton(token_id, hDAO_balance)}```, synced my wallet, and now its loading

**Comment by skenaja** [comment]
@violetforest - thanks for reporting, PR to fix unsynced accounts incoming

**Pull request merged**
